// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Comment struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	MovieID   int64     `json:"movie_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Movie struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Score       float64   `json:"score"`
	Image       string    `json:"image"`
	ReleaseDate time.Time `json:"release_date"`
}

type User struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	FirebaseUid string    `json:"firebase_uid"`
	Image       string    `json:"image"`
	Email       string    `json:"email"`
	CreatedAt   time.Time `json:"created_at"`
}

type WatchedMovie struct {
	UserID  int64 `json:"user_id"`
	MovieID int64 `json:"movie_id"`
}
